/*
 * generated by Xtext 2.21.0
 */
package uk.ac.ccpn.neftools;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class StarStandaloneSetup extends StarStandaloneSetupGenerated {

	public static void doSetup() {
		new StarStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
