/*
 * generated by Xtext 2.21.0
 */
package uk.ac.ccpn.neftools;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StarRuntimeModule extends AbstractStarRuntimeModule {
}
