/*
 * generated by Xtext 2.21.0
 */
package uk.ac.ccpn.neftools.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class StarUiModule extends AbstractStarUiModule {

	public StarUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
