/*
 * generated by Xtext 2.21.0
 */
package uk.ac.ccpn.neftools.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import uk.ac.ccpn.neftools.star.Star_file


@ExtendWith(InjectionExtension)
@InjectWith(StarInjectorProvider)
class StarParsingTest {
	@Inject
	ParseHelper<Star_file> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			data_123
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
